apiVersion: v1
kind: Service
metadata:
  name: homework-service
  namespace: homework
spec:
  type: ClusterIP
  selector:
    app: homework-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
